status is-interactive || exit

# --- Docker ---
abbr --add dbl 'docker build'
abbr --add dcin 'docker container inspect'
abbr --add dcls 'docker container ls'
abbr --add dclsa 'docker container ls -a'
abbr --add dib 'docker image build'
abbr --add dii 'docker image inspect'
abbr --add dils 'docker image ls'
abbr --add dipru 'docker image prune -a'
abbr --add dipu 'docker image push'
abbr --add dirm 'docker image rm'
abbr --add dit 'docker image tag'
abbr --add dlo 'docker container logs'
abbr --add dnc 'docker network create'
abbr --add dncn 'docker network connect'
abbr --add dndcn 'docker network disconnect'
abbr --add dni 'docker network inspect'
abbr --add dnls 'docker network ls'
abbr --add dnrm 'docker network rm'
abbr --add dpo 'docker container port'
abbr --add dps 'docker ps'
abbr --add dpsa 'docker ps -a'
abbr --add dpu 'docker pull'
abbr --add dr 'docker container run'
abbr --add drit 'docker container run -it'
abbr --add drm 'docker container rm'
abbr --add 'drm!' 'docker container rm -f'
abbr --add drs 'docker container restart'
abbr --add dst 'docker container start'
abbr --add dsta 'docker stop (docker ps -q)'
abbr --add dstp 'docker container stop'
abbr --add dsts 'docker stats'
abbr --add dvi 'docker volume inspect'
abbr --add dvls 'docker volume ls'
abbr --add dvprune 'docker volume prune'
abbr --add dxc 'docker container exec'
abbr --add dxcit 'docker container exec -it'

# --- Grep ---
abbr --add egrep 'grep -E'
abbr --add fgrep 'grep -F'

# --- Git ---
abbr --add g git
abbr --add ga 'git add'
abbr --add gaa 'git add --all'
abbr --add gam 'git am'
abbr --add gama 'git am --abort'
abbr --add gamc 'git am --continue'
abbr --add gams 'git am --skip'
abbr --add gamscp 'git am --show-current-patch'
abbr --add gap 'git apply'
abbr --add gapa 'git add --patch'
abbr --add gapt 'git apply --3way'
abbr --add gau 'git add --update'
abbr --add gav 'git add --verbose'
abbr --add gb 'git branch'
abbr --add 'gbD' 'git branch --delete --force'
abbr --add gba 'git branch --all'
abbr --add gbd 'git branch --delete'
abbr --add gbg 'LANG=C git branch -vv | grep ": gone]"'
abbr --add 'gbgD' 'LANG=C git branch --no-color -vv | grep ": gone]" | cut -c 3- | awk \'{print $1}\' | xargs git branch -D'
abbr --add gbgd 'LANG=C git branch --no-color -vv | grep ": gone]" | cut -c 3- | awk \'{print $1}\' | xargs git branch -d'
abbr --add gbl 'git blame -w'
abbr --add gbm 'git branch --move'
abbr --add gbnm 'git branch --no-merged'
abbr --add gbr 'git branch --remote'
abbr --add gbs 'git bisect'
abbr --add gbsb 'git bisect bad'
abbr --add gbsg 'git bisect good'
abbr --add gbsn 'git bisect new'
abbr --add gbso 'git bisect old'
abbr --add gbsr 'git bisect reset'
abbr --add gbss 'git bisect start'
abbr --add gc 'git commit --verbose'
abbr --add 'gc!' 'git commit --verbose --amend'
abbr --add 'gcB' 'git checkout -B'
abbr --add gca 'git commit --verbose --all'
abbr --add 'gca!' 'git commit --verbose --all --amend'
abbr --add gcam 'git commit --all --message'
abbr --add 'gcan!' 'git commit --verbose --all --no-edit --amend'
abbr --add 'gcann!' 'git commit --verbose --all --date=now --no-edit --amend'
abbr --add 'gcans!' 'git commit --verbose --all --signoff --no-edit --amend'
abbr --add gcas 'git commit --all --signoff'
abbr --add gcasm 'git commit --all --signoff --message'
abbr --add gcb 'git checkout -b'
abbr --add gcd 'git checkout (git_develop_branch)'
abbr --add gcf 'git config --list'
abbr --add gcfu 'git commit --fixup'
abbr --add gcl 'git clone --recurse-submodules'
abbr --add gclean 'git clean --interactive -d'
abbr --add gclf 'git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules'
abbr --add gcm 'git checkout (git_main_branch)'
abbr --add gcmsg 'git commit --message'
abbr --add gcn 'git commit --verbose --no-edit'
abbr --add 'gcn!' 'git commit --verbose --no-edit --amend'
abbr --add gco 'git checkout'
abbr --add gcor 'git checkout --recurse-submodules'
abbr --add gcount 'git shortlog --summary --numbered'
abbr --add gcp 'git cherry-pick'
abbr --add gcpa 'git cherry-pick --abort'
abbr --add gcpc 'git cherry-pick --continue'
abbr --add gcs 'git commit --gpg-sign'
abbr --add gcsm 'git commit --signoff --message'
abbr --add gcss 'git commit --gpg-sign --signoff'
abbr --add gcssm 'git commit --gpg-sign --signoff --message'
abbr --add gd 'git diff'
abbr --add gdca 'git diff --cached'
abbr --add gdct 'git describe --tags (git rev-list --tags --max-count=1)'
abbr --add gdcw 'git diff --cached --word-diff'
abbr --add gds 'git diff --staged'
abbr --add gdt 'git diff-tree --no-commit-id --name-only -r'
abbr --add gdup 'git diff @{upstream}'
abbr --add gdw 'git diff --word-diff'
abbr --add gf 'git fetch'
abbr --add gfa 'git fetch --all --tags --prune --jobs=10'
abbr --add gfg 'git ls-files | grep'
abbr --add gfo 'git fetch origin'
abbr --add gg 'git gui citool'
abbr --add gga 'git gui citool --amend'
abbr --add ggpull 'git pull origin (git_current_branch)'
abbr --add ggpush 'git push origin (git_current_branch)'
abbr --add ggsup 'git branch --set-upstream-to=origin/(git_current_branch)'
abbr --add ghh 'git help'
abbr --add gignore 'git update-index --assume-unchanged'
abbr --add gignored 'git ls-files -v | grep "^[[:lower:]]"'
abbr --add gk 'gitk --all --branches &'
abbr --add gke 'gitk --all (git log --walk-reflogs --pretty=%h) &'
abbr --add gl 'git pull'
abbr --add glg 'git log --stat'
abbr --add glgg 'git log --graph'
abbr --add glgga 'git log --graph --decorate --all'
abbr --add glgm 'git log --graph --max-count=10'
abbr --add glgp 'git log --stat --patch'
abbr --add glo 'git log --oneline --decorate'
abbr --add glod 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
abbr --add glods 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short'
abbr --add glog 'git log --oneline --decorate --graph'
abbr --add gloga 'git log --oneline --decorate --graph --all'
abbr --add glol 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
abbr --add glola 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --all'
abbr --add glols 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --stat'
abbr --add gluc 'git pull upstream (git_current_branch)'
abbr --add glum 'git pull upstream (git_main_branch)'
abbr --add gm 'git merge'
abbr --add gma 'git merge --abort'
abbr --add gmc 'git merge --continue'
abbr --add gmff 'git merge --ff-only'
abbr --add gmom 'git merge origin/(git_main_branch)'
abbr --add gms 'git merge --squash'
abbr --add gmtl 'git mergetool --no-prompt'
abbr --add gmtlvim 'git mergetool --no-prompt --tool=vimdiff'
abbr --add gmum 'git merge upstream/(git_main_branch)'
abbr --add gp 'git push'
abbr --add gpd 'git push --dry-run'
abbr --add gpf 'git push --force-with-lease --force-if-includes'
abbr --add 'gpf!' 'git push --force'
abbr --add gpoat 'git push origin --all && git push origin --tags'
abbr --add gpod 'git push origin --delete'
abbr --add gpr 'git pull --rebase'
abbr --add gpra 'git pull --rebase --autostash'
abbr --add gprav 'git pull --rebase --autostash -v'
abbr --add gpristine 'git reset --hard && git clean --force -dfx'
abbr --add gprom 'git pull --rebase origin (git_main_branch)'
abbr --add gpromi 'git pull --rebase=interactive origin (git_main_branch)'
abbr --add gprum 'git pull --rebase upstream (git_main_branch)'
abbr --add gprumi 'git pull --rebase=interactive upstream (git_main_branch)'
abbr --add gprv 'git pull --rebase -v'
abbr --add gpsup 'git push --set-upstream origin (git_current_branch)'
abbr --add gpsupf 'git push --set-upstream origin (git_current_branch) --force-with-lease --force-if-includes'
abbr --add gpu 'git push upstream'
abbr --add gpv 'git push --verbose'
abbr --add gr 'git remote'
abbr --add gra 'git remote add'
abbr --add grb 'git rebase'
abbr --add grba 'git rebase --abort'
abbr --add grbc 'git rebase --continue'
abbr --add grbd 'git rebase (git_develop_branch)'
abbr --add grbi 'git rebase --interactive'
abbr --add grbm 'git rebase (git_main_branch)'
abbr --add grbo 'git rebase --onto'
abbr --add grbom 'git rebase origin/(git_main_branch)'
abbr --add grbs 'git rebase --skip'
abbr --add grbum 'git rebase upstream/(git_main_branch)'
abbr --add grep 'grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox,.venv,venv}'
abbr --add grev 'git revert'
abbr --add greva 'git revert --abort'
abbr --add grevc 'git revert --continue'
abbr --add grf 'git reflog'
abbr --add grh 'git reset'
abbr --add grhh 'git reset --hard'
abbr --add grhk 'git reset --keep'
abbr --add grhs 'git reset --soft'
abbr --add grm 'git rm'
abbr --add grmc 'git rm --cached'
abbr --add grmv 'git remote rename'
abbr --add groh 'git reset origin/(git_current_branch) --hard'
abbr --add grrm 'git remote remove'
abbr --add grs 'git restore'
abbr --add grset 'git remote set-url'
abbr --add grss 'git restore --source'
abbr --add grst 'git restore --staged'
abbr --add grt 'cd (git rev-parse --show-toplevel || echo .)'
abbr --add gru 'git reset --'
abbr --add grup 'git remote update'
abbr --add grv 'git remote --verbose'
abbr --add gsb 'git status --short --branch'
abbr --add gsh 'git show'
abbr --add gsi 'git submodule init'
abbr --add gsps 'git show --pretty=short --show-signature'
abbr --add gss 'git status --short'
abbr --add gst 'git status'
abbr --add gsta 'git stash push'
abbr --add gstaa 'git stash apply'
abbr --add gstall 'git stash --all'
abbr --add gstc 'git stash clear'
abbr --add gstd 'git stash drop'
abbr --add gstl 'git stash list'
abbr --add gstp 'git stash pop'
abbr --add gsts 'git stash show --patch'
abbr --add gstu 'gsta --include-untracked'
abbr --add gsu 'git submodule update'
abbr --add gsw 'git switch'
abbr --add gswc 'git switch --create'
abbr --add gswd 'git switch (git_develop_branch)'
abbr --add gswm 'git switch (git_main_branch)'
abbr --add gta 'git tag --annotate'
abbr --add gts 'git tag --sign'
abbr --add gtv 'git tag | sort -V'
abbr --add gunignore 'git update-index --no-assume-unchanged'
abbr --add gunwip 'git rev-list --max-count=1 --format="%s" HEAD | grep -q "\--wip--" && git reset HEAD~1'
abbr --add gup gpr
abbr --add gupa gpra
abbr --add gupav gprav
abbr --add gupom gprom
abbr --add gupomi gpromi
abbr --add gupv gprv
abbr --add gwch 'git whatchanged -p --abbrev-commit --pretty=medium'
abbr --add gwip 'git add -A; git rm (git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"'
abbr --add gwipe 'git reset --hard && git clean --force -df'
abbr --add gwt 'git worktree'
abbr --add gwta 'git worktree add'
abbr --add gwtls 'git worktree list'
abbr --add gwtmv 'git worktree move'
abbr --add gwtrm 'git worktree remove'

# --- Go ---
abbr --add gob 'go build'
abbr --add goc 'go clean'
abbr --add god 'go doc'
abbr --add goe 'go env'
abbr --add gof 'go fmt'
abbr --add gofa 'go fmt ./...'
abbr --add gofx 'go fix'
abbr --add gog 'go get'
abbr --add goga 'go get ./...'
abbr --add goi 'go install'
abbr --add gol 'go list'
abbr --add gom 'go mod'
abbr --add gomt 'go mod tidy'
abbr --add gopa 'cd $GOPATH'
abbr --add gopb 'cd $GOPATH/bin'
abbr --add gops 'cd $GOPATH/src'
abbr --add gor 'go run'
abbr --add got 'go test'
abbr --add gota 'go test ./...'
abbr --add goto 'go tool'
abbr --add gotoc 'go tool compile'
abbr --add gotod 'go tool dist'
abbr --add gotofx 'go tool fix'
abbr --add gov 'go vet'
abbr --add gove 'go version'
abbr --add gow 'go work'

# --- System & Misc ---
abbr --add k kubectl
abbr --add kx 'kubectx'
abbr --add kn 'kubens'
abbr --add kgp 'kubectl get pods'
abbr --add kgpa 'kubectl get pods -A'
abbr --add kgn 'kubectl get nodes'
abbr --add kgs 'kubectl get svc'
abbr --add kgd 'kubectl get deployments'
abbr --add kga 'kubectl get all'
abbr --add kgaa 'kubectl get all -A'
abbr --add kd 'kubectl describe'
abbr --add kdp 'kubectl describe pod'
abbr --add kl 'kubectl logs'
abbr --add klf 'kubectl logs -f'
abbr --add ke 'kubectl exec -it'
abbr --add kaf 'kubectl apply -f'
abbr --add kdf 'kubectl delete -f'
abbr --add kdel 'kubectl delete'
abbr --add kctx 'kubectl config current-context'
abbr --add kgctx 'kubectl config get-contexts'
abbr --add ksns 'kubectl config set-context --current --namespace'
abbr --add kpf 'kubectl port-forward'
abbr --add ktp 'kubectl top pods'
abbr --add ktn 'kubectl top nodes'
abbr --add fr "flux reconcile"

# --- Helm ---
abbr --add hi 'helm install'
abbr --add hu 'helm upgrade'
abbr --add hud 'helm upgrade --install'
abbr --add hd 'helm delete'
abbr --add hls 'helm list'
abbr --add hlsa 'helm list -A'
abbr --add hrep 'helm repo'
abbr --add hrepa 'helm repo add'
abbr --add hrepu 'helm repo update'
abbr --add hrepl 'helm repo list'
abbr --add hs 'helm search'
abbr --add hsr 'helm search repo'
abbr --add hsh 'helm show'
abbr --add hshv 'helm show values'
abbr --add hg 'helm get'
abbr --add hgv 'helm get values'
abbr --add hst 'helm status'
abbr --add hrl 'helm rollback'
abbr --add hh 'helm history'
abbr --add ht 'helm template'
abbr --add cat 'bat -p --paging=never'
abbr --add catp bat
abbr --add h tldr
abbr --add hup 'tldr --update'
abbr --add lg lazygit
abbr --add lzd lazydocker
abbr --add l 'eza -lah'
abbr --add la 'eza -lAh'
abbr --add ll 'eza -lh'
abbr --add ls eza
abbr --add lsa 'eza -lah'
abbr --add lt 'eza --tree --level=2'
abbr --add md 'mkdir -p'
abbr --add pa 'source .venv/bin/activate.fish'
abbr --add py python3
abbr --add pyfind 'find . -name "*.py"'
abbr --add pygrep 'grep -nr --include="*.py"'
abbr --add pyserver 'python3 -m http.server'
abbr --add rd rmdir
abbr --add rgi 'rg -i'
abbr --add rfish 'source ~/.config/fish/config.fish'
abbr --add rzsh 'source ~/.config/fish/config.fish' # For muscle memory
abbr --add t 'uv run pytest --no-cov'
abbr --add zed zeditor

if test (uname) = Darwin
    abbr --add hidefiles 'defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
    abbr --add showfiles 'defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
end

# --- Terraform ---
abbr --add tf terraform
abbr --add tfa 'terraform apply'
abbr --add tfaa 'terraform apply -auto-approve'
abbr --add tfc 'terraform console'
abbr --add tfd 'terraform destroy'
abbr --add 'tfd!' 'terraform destroy -auto-approve'
abbr --add tff 'terraform fmt'
abbr --add tffr 'terraform fmt -recursive'
abbr --add tfi 'terraform init'
abbr --add tfir 'terraform init -reconfigure'
abbr --add tfiu 'terraform init -upgrade'
abbr --add tfiur 'terraform init -upgrade -reconfigure'
abbr --add tfo 'terraform output'
abbr --add tfp 'terraform plan'
abbr --add tfs 'terraform state'
abbr --add tfsh 'terraform show'
abbr --add tft 'terraform test'
abbr --add tfv 'terraform validate'

# --- UV ---
abbr --add uva 'uv add'
abbr --add uvexp 'uv export --format requirements-txt --no-hashes --output-file requirements.txt --quiet'
abbr --add uvl 'uv lock'
abbr --add uvlr 'uv lock --refresh'
abbr --add uvlu 'uv lock --upgrade'
abbr --add uvp 'uv pip'
abbr --add uvpy 'uv python'
abbr --add uvr 'uv run'
abbr --add uvrm 'uv remove'
abbr --add uvs 'uv sync'
abbr --add uvsr 'uv sync --refresh'
abbr --add uvsu 'uv sync --upgrade'
abbr --add uvup 'uv self update'
abbr --add uvv 'uv venv'
