k9s:
  cluster: homelab
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
      - kube-system
      - system-upgrade
      - network
      - matrix
      - dragonfly-system
      - home-assistant
      - volsync-system
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
