$hypr = ~/.config/hypr
$hl = $hypr/hyprland

# Monitor layout (DP-2 left, DP-1 right)
monitor = , preferred, auto, 1
monitor = DP-2, preferred, 0x0, 1
monitor = DP-1, preferred, 2560x0, 1

# Workspaces pinned to monitors (1-5 left, 6-10 right)
workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 10, monitor:DP-1

# env, input/NVIDIA cursor, vrr/misc, autostart, window rules
source = $hl/env.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/execs.conf
source = $hl/rules.conf

# Appearance and keybinds
source = $hl/appearance.conf
source = $hl/binds.conf

# OVERRIDES
# Anything written below overrides the sourced files above.

# For Noctalia Color templates
source = ~/.config/hypr/noctalia.conf
